services:
  sql_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab4_sql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sql_app:
    build:
      context: lab4_sql
    container_name: sql_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lab4_sql:/usr/src/lab4_sql
    ports:
      - "8000:8000"
    depends_on:
      sql_db:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/lab4_sql

volumes:
  postgres_data: null