# Generated by Django 3.1.12 on 2024-12-16 21:37

import django.core.validators
from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20241216_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='picture',
            field=models.ImageField(blank=True, upload_to=sales.models.generate_unique_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sales.models.validate_image_mime_type]),
        ),
    ]
