# Generated by Django 3.1.12 on 2024-12-18 13:25

import django.core.validators
from django.db import migrations
import django_resized.forms
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20241216_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to=sales.models.generate_unique_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sales.models.validate_image_mime_type]),
        ),
    ]
